<a href="https://colab.research.google.com/github/ambika1us/Global-Terrorism-Analysis/blob/main/Global_Terrorism_Analysis_Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <b> The Global Terrorism Database (GTD) is an open-source database including information on terrorist attacks around the world from 1970 through 2017. The GTD includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period and now includes more than 180,000 attacks. The database is maintained by researchers at the National Consortium for the Study of Terrorism and Responses to Terrorism (START), headquartered at the University of Maryland.</b>

# <b> Explore and analyze the data to discover key findings pertaining to terrorist activities. </b>

<B>Working with Dataset</B>

In [ ]:
#Let's start by importing some required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Both matplotlib and seaborn are very popular libraries that are used for visualizations. Import warning and see it to ignore to just ignore all the warnings.<BR>
Now import the dataset using read_csv

In [ ]:
#import terrorism dataset
terr_data=pd.read_csv('/content/drive/MyDrive/AlmaBetter/EDA_Project_1/Global Terrorism Data Analysis/Global Terrorism Data.csv',encoding='ISO-8859-1')

In [ ]:
#View the dataset
terr_data

eventid  iyear  imonth  iday approxdate  extended resolution  \
0       197000000001   1970       7     2        NaN         0        NaN   
1       197000000002   1970       0     0        NaN         0        NaN   
2       197001000001   1970       1     0        NaN         0        NaN   
3       197001000002   1970       1     0        NaN         0        NaN   
4       197001000003   1970       1     0        NaN         0        NaN   
...              ...    ...     ...   ...        ...       ...        ...   
181686  201712310022   2017      12    31        NaN         0        NaN   
181687  201712310029   2017      12    31        NaN         0        NaN   
181688  201712310030   2017      12    31        NaN         0        NaN   
181689  201712310031   2017      12    31        NaN         0        NaN   
181690  201712310032   2017      12    31        NaN         0        NaN   

        country         country_txt  region  ... addnotes  \
0            58  Dominican Republic       2  ...      NaN   
1           130              Mexico       1  ...      NaN   
2           160         Philippines       5  ...      NaN   
3            78              Greece       8  ...      NaN   
4           101               Japan       4  ...      NaN   
...         ...                 ...     ...  ...      ...   
181686      182             Somalia      11  ...      NaN   
181687      200               Syria      10  ...      NaN   
181688      160         Philippines       5  ...      NaN   
181689       92               India       6  ...      NaN   
181690      160         Philippines       5  ...      NaN   

                                                   scite1  \
0                                                     NaN   
1                                                     NaN   
2                                                     NaN   
3                                                     NaN   
4                                                     NaN   
...                                                   ...   
181686  "Somalia: Al-Shabaab Militants Attack Army Che...   
181687  "Putin's 'victory' in Syria has turned into a ...   
181688  "Maguindanao clashes trap tribe members," Phil...   
181689  "Trader escapes grenade attack in Imphal," Bus...   
181690  "Security tightened in Cotabato following IED ...   

                                                   scite2  \
0                                                     NaN   
1                                                     NaN   
2                                                     NaN   
3                                                     NaN   
4                                                     NaN   
...                                                   ...   
181686  "Highlights: Somalia Daily Media Highlights 2 ...   
181687  "Two Russian soldiers killed at Hmeymim base i...   
181688                                                NaN   
181689                                                NaN   
181690  "Security tightened in Cotabato City," Manila ...   

                                                   scite3  \
0                                                     NaN   
1                                                     NaN   
2                                                     NaN   
3                                                     NaN   
4                                                     NaN   
...                                                   ...   
181686  "Highlights: Somalia Daily Media Highlights 1 ...   
181687  "Two Russian servicemen killed in Syria mortar...   
181688                                                NaN   
181689                                                NaN   
181690                                                NaN   

                        dbsource  INT_LOG  INT_IDEO INT_MISC INT_ANY  related  
0                           PGIS        0         0        0       0      Na

In [ ]:
#Now view the shape
print("There are {} rows and {} column in the dataset".format(terr_data.shape[0],terr_data.shape[1]))

There are 181691 rows and 135 column in the dataset


In [ ]:
#Now view all the columns in the data frame
terr_data.columns

Index(['eventid', 'iyear', 'imonth', 'iday', 'approxdate', 'extended',
       'resolution', 'country', 'country_txt', 'region',
       ...
       'addnotes', 'scite1', 'scite2', 'scite3', 'dbsource', 'INT_LOG',
       'INT_IDEO', 'INT_MISC', 'INT_ANY', 'related'],
      dtype='object', length=135)

In [ ]:
#View the total number of unique columns in the dataset
no_of_cols=terr_data.columns.nunique()
print("There are total %d columns in the data" %no_of_cols)

There are total 135 columns in the data


<B>Rename some columns which we are going to use for analysis</B>

In [ ]:
#let's rename some important columns
terr_data=terr_data.rename(columns={'iyear':'Year','imonth':'Month','iday':'Day','country_txt':'Country','region_txt':'Region','provstate':'State',
                                   'city':'City','attacktype1_txt':'Attack_type','targtype1_txt':'Target_type','targsubtype1_txt':'Target_subtype',
                                   'gname':'Gang_name'})
terr_data.columns

Index(['Year', 'Month', 'Day', 'Country', 'Region', 'State', 'City',
       'Attack_type', 'Target_type', 'Target_subtype', 'Gang_name'],
      dtype='object')

<B>Check if the column names were updated.</B>

In [ ]:
#Columns names were updated in this data frame
terr_data

Year  Month  Day             Country                       Region  \
0       1970      7    2  Dominican Republic  Central America & Caribbean   
1       1970      0    0              Mexico                North America   
2       1970      1    0         Philippines               Southeast Asia   
3       1970      1    0              Greece               Western Europe   
4       1970      1    0               Japan                    East Asia   
...      ...    ...  ...                 ...                          ...   
181686  2017     12   31             Somalia           Sub-Saharan Africa   
181687  2017     12   31               Syria   Middle East & North Africa   
181688  2017     12   31         Philippines               Southeast Asia   
181689  2017     12   31               India                   South Asia   
181690  2017     12   31         Philippines               Southeast Asia   

                  State           City                     Attack_type  \
0               Unknown  Santo Domingo                   Assassination   
1               Federal    Mexico city     Hostage Taking (Kidnapping)   
2                Tarlac        Unknown                   Assassination   
3                Attica         Athens               Bombing/Explosion   
4               Fukouka        Fukouka  Facility/Infrastructure Attack   
...                 ...            ...                             ...   
181686  Middle Shebelle  Ceelka Geelow                   Armed Assault   
181687         Lattakia         Jableh               Bombing/Explosion   
181688      Maguindanao       Kubentog  Facility/Infrastructure Attack   
181689          Manipur         Imphal               Bombing/Explosion   
181690      Maguindanao  Cotabato City               Bombing/Explosion   

                        Target_type  \
0       Private Citizens & Property   
1           Government (Diplomatic)   
2               Journalists & Media   
3           Government (Diplomatic)   
4           Government (Diplomatic)   
...                             ...   
181686                     Military   
181687                     Military   
181688  Private Citizens & Property   
181689         Government (General)   
181690                      Unknown   

                                           Target_subtype  \
0                                          Named Civilian   
1       Diplomatic Personnel (outside of embassy, cons...   
2                         Radio Journalist/Staff/Facility   
3                                       Embassy/Consulate   
4                                       Embassy/Consulate   
...                                                   ...   
181686                                Military Checkpoint   
181687      Military Barracks/Base/Headquarters/Checkpost   
181688                          House/Apartment/Residence   
181689                Government Building/Facility/Office   
181690                                             others   

                                         Gang_name  
0                                           MANO-D  
1               23rd of September Communist League  
2                                          Unknown  
3                                          Unknown  
4                                          Unknown  
...                                            ...  
181686                                  Al-Shabaab  
181687                           Muslim extremists  
181688  Bangsamoro Islamic Freedom Movement (BIFM)  
181689                                     Unknown  
181690                                     Unknown  

[181691 rows x 11 columns]

<B>Now take only those columns which are required for analysis in the dataset</b>

In [ ]:
terr_data=terr_data[['Year','Month','Day','Country','Region','State','City','Attack_type','Target_type','Target_subtype','Gang_name']]
terr_data.columns
#Check if it's updated

Index(['Year', 'Month', 'Day', 'Country', 'Region', 'State', 'City',
       'Attack_type', 'Target_type', 'Target_subtype', 'Gang_name'],
      dtype='object')

In [ ]:
#Our new dataframe
terr_data

Year  Month  Day             Country                       Region  \
0       1970      7    2  Dominican Republic  Central America & Caribbean   
1       1970      0    0              Mexico                North America   
2       1970      1    0         Philippines               Southeast Asia   
3       1970      1    0              Greece               Western Europe   
4       1970      1    0               Japan                    East Asia   
...      ...    ...  ...                 ...                          ...   
181686  2017     12   31             Somalia           Sub-Saharan Africa   
181687  2017     12   31               Syria   Middle East & North Africa   
181688  2017     12   31         Philippines               Southeast Asia   
181689  2017     12   31               India                   South Asia   
181690  2017     12   31         Philippines               Southeast Asia   

                  State           City                     Attack_type  \
0               Unknown  Santo Domingo                   Assassination   
1               Federal    Mexico city     Hostage Taking (Kidnapping)   
2                Tarlac        Unknown                   Assassination   
3                Attica         Athens               Bombing/Explosion   
4               Fukouka        Fukouka  Facility/Infrastructure Attack   
...                 ...            ...                             ...   
181686  Middle Shebelle  Ceelka Geelow                   Armed Assault   
181687         Lattakia         Jableh               Bombing/Explosion   
181688      Maguindanao       Kubentog  Facility/Infrastructure Attack   
181689          Manipur         Imphal               Bombing/Explosion   
181690      Maguindanao  Cotabato City               Bombing/Explosion   

                        Target_type  \
0       Private Citizens & Property   
1           Government (Diplomatic)   
2               Journalists & Media   
3           Government (Diplomatic)   
4           Government (Diplomatic)   
...                             ...   
181686                     Military   
181687                     Military   
181688  Private Citizens & Property   
181689         Government (General)   
181690                      Unknown   

                                           Target_subtype  \
0                                          Named Civilian   
1       Diplomatic Personnel (outside of embassy, cons...   
2                         Radio Journalist/Staff/Facility   
3                                       Embassy/Consulate   
4                                       Embassy/Consulate   
...                                                   ...   
181686                                Military Checkpoint   
181687      Military Barracks/Base/Headquarters/Checkpost   
181688                          House/Apartment/Residence   
181689                Government Building/Facility/Office   
181690                                             others   

                                         Gang_name  
0                                           MANO-D  
1               23rd of September Communist League  
2                                          Unknown  
3                                          Unknown  
4                                          Unknown  
...                                            ...  
181686                                  Al-Shabaab  
181687                           Muslim extremists  
181688  Bangsamoro Islamic Freedom Movement (BIFM)  
181689                                     Unknown  
181690                                     Unknown  

[181691 rows x 11 columns]

<B>Now make some changes that are required for the dataset

In [ ]:
#Fill NaN values in Target_Subtype column as others
terr_data['Target_subtype']=terr_data['Target_subtype'].fillna('others')

In [ ]:
#Fill NaN values in the city column as Unknown
terr_data['City']=terr_data['City'].fillna('Unknown')

In [ ]:
#Fill NaN values in the state column as Unknown
terr_data['State']=terr_data['State'].fillna('Unknown')

In [ ]:
#This is our final update data frame
terr_data

Year  Month  Day             Country                       Region  \
0       1970      7    2  Dominican Republic  Central America & Caribbean   
1       1970      0    0              Mexico                North America   
2       1970      1    0         Philippines               Southeast Asia   
3       1970      1    0              Greece               Western Europe   
4       1970      1    0               Japan                    East Asia   
...      ...    ...  ...                 ...                          ...   
181686  2017     12   31             Somalia           Sub-Saharan Africa   
181687  2017     12   31               Syria   Middle East & North Africa   
181688  2017     12   31         Philippines               Southeast Asia   
181689  2017     12   31               India                   South Asia   
181690  2017     12   31         Philippines               Southeast Asia   

                  State           City                     Attack_type  \
0               Unknown  Santo Domingo                   Assassination   
1               Federal    Mexico city     Hostage Taking (Kidnapping)   
2                Tarlac        Unknown                   Assassination   
3                Attica         Athens               Bombing/Explosion   
4               Fukouka        Fukouka  Facility/Infrastructure Attack   
...                 ...            ...                             ...   
181686  Middle Shebelle  Ceelka Geelow                   Armed Assault   
181687         Lattakia         Jableh               Bombing/Explosion   
181688      Maguindanao       Kubentog  Facility/Infrastructure Attack   
181689          Manipur         Imphal               Bombing/Explosion   
181690      Maguindanao  Cotabato City               Bombing/Explosion   

                        Target_type  \
0       Private Citizens & Property   
1           Government (Diplomatic)   
2               Journalists & Media   
3           Government (Diplomatic)   
4           Government (Diplomatic)   
...                             ...   
181686                     Military   
181687                     Military   
181688  Private Citizens & Property   
181689         Government (General)   
181690                      Unknown   

                                           Target_subtype  \
0                                          Named Civilian   
1       Diplomatic Personnel (outside of embassy, cons...   
2                         Radio Journalist/Staff/Facility   
3                                       Embassy/Consulate   
4                                       Embassy/Consulate   
...                                                   ...   
181686                                Military Checkpoint   
181687      Military Barracks/Base/Headquarters/Checkpost   
181688                          House/Apartment/Residence   
181689                Government Building/Facility/Office   
181690                                             others   

                                         Gang_name  
0                                           MANO-D  
1               23rd of September Communist League  
2                                          Unknown  
3                                          Unknown  
4                                          Unknown  
...                                            ...  
181686                                  Al-Shabaab  
181687                           Muslim extremists  
181688  Bangsamoro Islamic Freedom Movement (BIFM)  
181689                                     Unknown  
181690                                     Unknown  

[181691 rows x 11 columns]

In [ ]:
#Now view the shape
terr_data.shape

(181691, 11)

Now there are only 11 columns and 181691 rows

In [ ]:
#Check for null values
terr_data.isnull().sum()

Year              0
Month             0
Day               0
Country           0
Region            0
State             0
City              0
Attack_type       0
Target_type       0
Target_subtype    0
Gang_name         0
dtype: int64

There are no null values over the entire data

In [ ]:
#View top 10 rows of data
terr_data.head(10)

Year  Month  Day             Country                       Region  \
0  1970      7    2  Dominican Republic  Central America & Caribbean   
1  1970      0    0              Mexico                North America   
2  1970      1    0         Philippines               Southeast Asia   
3  1970      1    0              Greece               Western Europe   
4  1970      1    0               Japan                    East Asia   
5  1970      1    1       United States                North America   
6  1970      1    2             Uruguay                South America   
7  1970      1    2       United States                North America   
8  1970      1    2       United States                North America   
9  1970      1    3       United States                North America   

        State           City                     Attack_type  \
0     Unknown  Santo Domingo                   Assassination   
1     Federal    Mexico city     Hostage Taking (Kidnapping)   
2      Tarlac        Unknown                   Assassination   
3      Attica         Athens               Bombing/Explosion   
4     Fukouka        Fukouka  Facility/Infrastructure Attack   
5    Illinois          Cairo                   Armed Assault   
6  Montevideo     Montevideo                   Assassination   
7  California        Oakland               Bombing/Explosion   
8   Wisconsin        Madison  Facility/Infrastructure Attack   
9   Wisconsin        Madison  Facility/Infrastructure Attack   

                   Target_type  \
0  Private Citizens & Property   
1      Government (Diplomatic)   
2          Journalists & Media   
3      Government (Diplomatic)   
4      Government (Diplomatic)   
5                       Police   
6                       Police   
7                    Utilities   
8                     Military   
9         Government (General)   

                                      Target_subtype  \
0                                     Named Civilian   
1  Diplomatic Personnel (outside of embassy, cons...   
2                    Radio Journalist/Staff/Facility   
3                                  Embassy/Consulate   
4                                  Embassy/Consulate   
5    Police Building (headquarters, station, school)   
6                    Police Security Forces/Officers   
7                                        Electricity   
8                Military Recruiting Station/Academy   
9                Government Building/Facility/Office   

                            Gang_name  
0                              MANO-D  
1  23rd of September Communist League  
2                             Unknown  
3                             Unknown  
4                             Unknown  
5                  Black Nationalists  
6                 Tupamaros (Uruguay)  
7                             Unknown  
8                     New Year's Gang  
9                     New Year's Gang

In [ ]:
#View unique column names
terr_data.columns.unique()

Index(['Year', 'Month', 'Day', 'Country', 'Region', 'State', 'City',
       'Attack_type', 'Target_type', 'Target_subtype', 'Gang_name'],
      dtype='object')

In [ ]:
#Number of columns in the data set
terr_data.columns.unique()
Total_contries=list(terr_data['Country'].unique())
Total_contries=len(Total_contries)
print("Total %d Countries were noted in the data"%Total_contries)

Total 205 Countries were noted in the data


In [ ]:
print(terr_data['Region'].nunique())

12


In [ ]:
print(terr_data['Attack_type'].unique())
print(terr_data['Target_type'].unique())
print(terr_data['Gang_name'].unique())
print(terr_data['Gang_name'].nunique())

['Assassination' 'Hostage Taking (Kidnapping)' 'Bombing/Explosion'
 'Facility/Infrastructure Attack' 'Armed Assault' 'Hijacking' 'Unknown'
 'Unarmed Assault' 'Hostage Taking (Barricade Incident)']
['Private Citizens & Property' 'Government (Diplomatic)'
 'Journalists & Media' 'Police' 'Utilities' 'Military'
 'Government (General)' 'Airports & Aircraft' 'Business'
 'Educational Institution' 'Violent Political Party'
 'Religious Figures/Institutions' 'Unknown' 'Transportation' 'Tourists'
 'NGO' 'Telecommunication' 'Food or Water Supply'
 'Terrorists/Non-State Militia' 'Other' 'Maritime' 'Abortion Related']
['MANO-D' '23rd of September Communist League' 'Unknown' ...
 'Fatoni Warriors' 'Minorities of Metropolitan Attacks'
 'Baloch Republican Party']
3537


There are total 3537 gangs in this dataset

In [ ]:
#view the statistical description of the dataset
terr_data.describe()

Year          Month            Day
count  181691.000000  181691.000000  181691.000000
mean     2002.638997       6.467277      15.505644
std        13.259430       3.388303       8.814045
min      1970.000000       0.000000       0.000000
25%      1991.000000       4.000000       8.000000
50%      2009.000000       6.000000      15.000000
75%      2014.000000       9.000000      23.000000
max      2017.000000      12.000000      31.000000

In [ ]:
#View top 10 contries
terr_data['Country'].value_counts().head(10)
#There were top 10 affected contires

Iraq              24636
Pakistan          14368
Afghanistan       12731
India             11960
Colombia           8306
Philippines        6908
Peru               6096
El Salvador        5320
United Kingdom     5235
Turkey             4292
Name: Country, dtype: int64

In [ ]:
#Top 10 affected reasion
terr_data['Region'].value_counts().head(10)

Middle East & North Africa     50474
South Asia                     44974
South America                  18978
Sub-Saharan Africa             17550
Western Europe                 16639
Southeast Asia                 12485
Central America & Caribbean    10344
Eastern Europe                  5144
North America                   3456
East Asia                        802
Name: Region, dtype: int64

In [ ]:
#Top 10 affected states
terr_data['State'].value_counts().head(10)

Baghdad               7645
Unknown               4711
Northern Ireland      4498
Balochistan           3710
Saladin               3411
Al Anbar              3299
Nineveh               3241
Sindh                 3206
Khyber Pakhtunkhwa    3084
Diyala                3041
Name: State, dtype: int64

In [ ]:
#Top 10 Target subtype
terr_data['Target_subtype'].value_counts().head(10)

Unnamed Civilian/Unspecified                               11596
Police Security Forces/Officers                            11178
others                                                     10373
Military Unit/Patrol/Convoy                                 8277
Military Personnel (soldiers, troops, officers, forces)     7963
Government Personnel (excluding police, military)           6610
Village/City/Town/Suburb                                    6542
Politician or Political Party Movement/Meeting/Rally        6306
Police Building (headquarters, station, school)             5907
Military Barracks/Base/Headquarters/Checkpost               5211
Name: Target_subtype, dtype: int64

In [ ]:
#Top 10 affected City
terr_data['City'].value_counts().head(10)

Unknown         10209
Baghdad          7589
Karachi          2652
Lima             2359
Mosul            2265
Belfast          2171
Santiago         1621
Mogadishu        1581
San Salvador     1558
Istanbul         1048
Name: City, dtype: int64

In [ ]:
#Top 10 attacking modes
terr_data['Attack_type'].value_counts().head(10)

Bombing/Explosion                      88255
Armed Assault                          42669
Assassination                          19312
Hostage Taking (Kidnapping)            11158
Facility/Infrastructure Attack         10356
Unknown                                 7276
Unarmed Assault                         1015
Hostage Taking (Barricade Incident)      991
Hijacking                                659
Name: Attack_type, dtype: int64

In [ ]:
#Top 10 Target to attack
terr_data['Target_type'].value_counts().head(10)

Private Citizens & Property       43511
Military                          27984
Police                            24506
Government (General)              21283
Business                          20669
Transportation                     6799
Utilities                          6023
Unknown                            5898
Religious Figures/Institutions     4440
Educational Institution            4322
Name: Target_type, dtype: int64

In [ ]:
#Top 10 leading and most dangerious Gangs
terr_data['Gang_name'].value_counts().head(10)

Unknown                                             82782
Taliban                                              7478
Islamic State of Iraq and the Levant (ISIL)          5613
Shining Path (SL)                                    4555
Farabundo Marti National Liberation Front (FMLN)     3351
Al-Shabaab                                           3288
New People's Army (NPA)                              2772
Irish Republican Army (IRA)                          2671
Revolutionary Armed Forces of Colombia (FARC)        2487
Boko Haram                                           2418
Name: Gang_name, dtype: int64

In [ ]:
#Top 10 Year where attack were most happened
terr_data['Year'].value_counts().head(10)

2014    16903
2015    14965
2016    13587
2013    12036
2017    10900
2012     8522
2011     5076
1992     5071
2010     4826
2008     4805
Name: Year, dtype: int64

<B>Visualizations</B><BR>
Now let us find some hot zones using visualizations. For thsis, we have to use matplotlib and seaborn which we have installed at the begining.